### ISSUE TITLE
REPORTING

### ISSUE THREAD

**Issue by RoyalDrive** [Royal-Drive/DMS#104]
### Report Type: `dropdown`
- Unsold Cars:
    - Projected Revenue (Gross Income)
        - = total Listing Price of all inventory OR total $ in vehicle if no data in Listing Price
    - Projected Profit (Net Income)
        - = total projected profit of all inventory
- Sold Cars:
    - Revenue (Gross Income)
    - Profit (Net Income)
    - Sold Car Qty
    - Sales Sources:
        - list of qty of sales from each source
        - example:
            | Source | QTY |
            |--|--|
            | craigslist | 5 |
            | facebook | 10 |
            | personal | 3 |
            | Cargurus | 45 |

### Date Periods: `month/year picker(s)`
- Month and/or Year
- allow selecting many for comparison

### Custom Date Ranges: `date picker(s)`
- Start Date and End Date
- allow selecting many for comparison

**Comment by RoyalDrive** [comment]
Find sales data on:

 - Gross sales for the month (select a month)
 - Gross sales year to date

 - Net profit for the month (select a month)
 - Net profit year to date

 - Number of cars sold for the month (select a month)
 - Number of cars sold year to date

 - Projected gross income (formula = total Listing Price of all inventory OR total $ in vehicle if no data in Listing Price)
 - Projected net income (formula = total projected profit of all inventory) 

Might be more, but that's just a start! 
Other ideas: 
 - ways to compare year or month data to another year/month

**Comment by JacobWeisenburger** [comment]
Would you say that below is a good summary of what you are asking for?

___
## Controls
### Report Type: dropdown
- Revenue (Gross Income)
- Profit (Net Income)
- Sold Car Qty
- Projected Revenue (Gross Income)
    - = total Listing Price of all inventory OR total $ in vehicle if no data in Listing Price
- Projected Profit (Net Income)
    - = total projected profit of all inventory

### Date Periods: month/year picker(s)
- Month and/or Year
- allow selecting many for comparison

### Custom Date Ranges: date picker(s)
- Start Date and End Date
- allow selecting many for comparison

**Comment by RoyalDrive** [comment]
YES!

**Comment by RoyalDrive** [comment]
New section to add to reporting!

Source of sale: 
- craigslist
- facebook
- personal
- Cargurus
- walk-in
- etc

**Comment by JacobWeisenburger** [comment]
first post was updated to reflect source of sale

**Comment by JacobWeisenburger** [comment]
for the date selectors, which date are you wanting them to use?
Acquired Date?
Work Status Date?
Sale Status Date?
Listing Date?
Sale Date?

**Comment by JacobWeisenburger** [comment]
1. which icon do you like?
![image](https://user-images.githubusercontent.com/31667350/160252631-2cfe4fe1-a7b7-4ae0-9f5e-95dd7cae6412.png)

---
2. thoughts? anything look off? I mean obviously the numbers are incorrect, but I'm just making sure it looks the way you want it
![image](https://user-images.githubusercontent.com/31667350/160252638-28849c0e-d4b8-4efc-94ac-89ec27cab9ee.png)

---
3. I talked it over with Missy, and it seems to us that it doesn't make sense to have the Projected Revenue/Profit change based on the selected months. Because you don't ever know when your cars are going to sell so I'm thinking it might make more sense to show those here:
![image](https://user-images.githubusercontent.com/31667350/160252776-08299957-6012-46ef-9151-ccc34aad385f.png)

**Comment by RoyalDrive** [comment]
1. Any icon looks good to me :) 
2. wow I freaking love the format/layout you made. It looks perfect.
3. And yes, absolutely - put the projected profit right there.

On a side note: 
The projected profit will have to not include any vehicles not owned by Royal Drive in the owner drop down.
